# Generated by Django 3.2.8 on 2021-11-28 15:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtaqueVocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Ataque Vocal',
            },
        ),
        migrations.CreateModel(
            name='avaliacaoad_avaliacaoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataAvaliacao', models.DateField(default=datetime.datetime.now)),
                ('QOrelha', models.CharField(choices=[('ES', 'ESQUERDA'), ('DI', 'DIREITA'), ('AM', 'AMBAS')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='comunicoral_comunicoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_habilidade', models.CharField(max_length=150, verbose_name='Descrição da Habilidade')),
            ],
        ),
        migrations.CreateModel(
            name='Loudness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Loudness',
            },
        ),
        migrations.CreateModel(
            name='Modulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Modulação',
            },
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Pitch',
            },
        ),
        migrations.CreateModel(
            name='profissionalenc_profissionalenc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('0', 'Inativo')], max_length=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Qualidadeemis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Qualidade na Emissão',
            },
        ),
        migrations.CreateModel(
            name='Ressonancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Ressonancia',
            },
        ),
        migrations.CreateModel(
            name='TipoVoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Tipo de Voz',
            },
        ),
        migrations.CreateModel(
            name='TipoVozCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repostas', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.avaliacaoad_avaliacaoad', verbose_name='Avaliação')),
                ('tipovoz_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.tipovoz', verbose_name='Tipo de Voz')),
            ],
            options={
                'verbose_name_plural': 'Repostas da Pergunta Tipo Voz',
            },
        ),
        migrations.CreateModel(
            name='RessonanciaCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.avaliacaoad_avaliacaoad')),
                ('ressonancia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.ressonancia')),
            ],
            options={
                'verbose_name_plural': 'Repostas das Perguntas Ressonancia',
            },
        ),
        migrations.CreateModel(
            name='QualidadeemisCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.avaliacaoad_avaliacaoad')),
                ('qualidadeemis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.qualidadeemis')),
            ],
        ),
        migrations.CreateModel(
            name='PitchCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.avaliacaoad_avaliacaoad')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='paciente_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RG', models.CharField(max_length=12)),
                ('CPF', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('DataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('DataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do cadastro')),
                ('DataAtualizacao', models.DateTimeField(auto_now=True, verbose_name='Data da ultima atualização')),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=9, verbose_name='Sexo')),
                ('Profissional_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.profissionalenc_profissionalenc', verbose_name='Profissional Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='ModulacaoCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.avaliacaoad_avaliacaoad')),
                ('modulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.modulacao')),
            ],
        ),
        migrations.CreateModel(
            name='LoudnessCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.avaliacaoad_avaliacaoad')),
                ('loudness', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.loudness')),
            ],
        ),
        migrations.CreateModel(
            name='comunicoralidade_comunicoralidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_oralidade', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1, verbose_name='Resp. Oralidade')),
                ('ComunicOral_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.comunicoral_comunicoral', verbose_name='Comunicação Oral')),
                ('avaliacaoAD_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.avaliacaoad_avaliacaoad', verbose_name='Avaliação')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacaoad_avaliacaoad',
            name='paciente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.paciente_paciente'),
        ),
        migrations.CreateModel(
            name='AtaqueVocalCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('ataquevocal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.ataquevocal')),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaAurifono.avaliacaoad_avaliacaoad')),
            ],
        ),
    ]
