# Generated by Django 3.2.8 on 2021-10-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicOral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_habilidade', models.CharField(max_length=150)),
            ],
        ),
    ]
