# Generated by Django 3.2.8 on 2021-10-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComunicOral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicoral',
            options={'verbose_name_plural': 'Comunicação Oral Perguntas'},
        ),
    ]
