# Generated by Django 3.2.8 on 2021-11-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loudness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loudness',
            options={'verbose_name_plural': 'Loudness'},
        ),
    ]
