# Generated by Django 3.2.8 on 2021-11-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitch',
            options={'verbose_name_plural': 'Pitch'},
        ),
    ]
