# Generated by Django 3.2.8 on 2021-11-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalEnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('N', 'Não Ativo')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Cadastro de Profissionais',
            },
        ),
    ]
