# Generated by Django 3.2.8 on 2021-11-28 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfissionalEnc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('RG', models.CharField(max_length=14)),
                ('CPF', models.CharField(max_length=14)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=10)),
                ('DataCadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('DataNascimento', models.DateTimeField(blank=True)),
                ('Profissional_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfissionalEnc.profissionalenc')),
            ],
            options={
                'verbose_name_plural': 'Cadastro de Pacientes',
            },
        ),
    ]
