# Generated by Django 3.2.8 on 2021-11-28 12:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulacao', '0001_initial'),
        ('tipodevoz', '0001_initial'),
        ('pitch', '0001_initial'),
        ('ataquevocal', '0001_initial'),
        ('loudness', '0001_initial'),
        ('qualidadeemis', '0001_initial'),
        ('ressonancia', '0001_initial'),
        ('paciente', '0001_initial'),
        ('ComunicOral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataAvaliacao', models.DateTimeField(default=datetime.datetime.now)),
                ('QOrelha', models.CharField(choices=[('OE', 'Orelha Esquerda'), ('OD', 'Orelha Direita'), ('AM', 'Ambas')], max_length=2)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.paciente')),
            ],
            options={
                'verbose_name_plural': 'Avaliação Adulto',
            },
        ),
        migrations.CreateModel(
            name='TipoVozCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repostas', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('tipovoz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipodevoz.tipovoz')),
            ],
            options={
                'verbose_name_plural': 'Repostas da Pergunta Tipo Voz',
            },
        ),
        migrations.CreateModel(
            name='RessonanciaCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('ressonancia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ressonancia.ressonancia')),
            ],
            options={
                'verbose_name_plural': 'Repostas das Perguntas Ressonancia',
            },
        ),
        migrations.CreateModel(
            name='QualidadeemisCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('qualidadeemis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qualidadeemis.qualidadeemis')),
            ],
        ),
        migrations.CreateModel(
            name='PitchCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pitch.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='ModulacaoCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('modulacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulacao.modulacao')),
            ],
        ),
        migrations.CreateModel(
            name='LoudnessCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('loudness', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loudness.loudness')),
            ],
        ),
        migrations.CreateModel(
            name='ComunicOralidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_oralidade', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('ComunicOral', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ComunicOral.comunicoral')),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
            ],
            options={
                'verbose_name_plural': 'Respostas das Perguntas',
            },
        ),
        migrations.CreateModel(
            name='AtaqueVocalCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('ataquevocal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ataquevocal.ataquevocal')),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
            ],
        ),
    ]
