# Generated by Django 3.2.8 on 2021-11-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressonancia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ressonancia',
            options={'verbose_name_plural': 'Tipo de Ressonancia'},
        ),
    ]
